### ISSUE TITLE
Change logic for hits, so civilian ships will sink after one hit

### ISSUE THREAD

**Issue by CaitlinBerger** [OSU-CS361-W17/group11_project3#4]

**Comment by gbauer9** [comment]
I can do this

**Comment by gbauer9** [comment]
What should I do for this? There's no check to see if a ship is sinking, so should I just have it hit all of the ship's boxes?

**Comment by anish-94** [comment]
Just check what is changing the color of the board to red on hit. I would change all of the boxes of the civilian ship to red if one is hit.
