### ISSUE TITLE
Have 3 UML diagrams (current, expected, final) for the class structure

### ISSUE THREAD

**Issue by anish-94** [OSU-CS361-W17/group11_project3#6]

**Comment by RiverHendriksen** [comment]
I can work on the pre uml diagram

**Comment by CaitlinBerger** [comment]
We each need to create at least 1 UML class/sequence diagram, How should we split this up?

**Comment by RiverHendriksen** [comment]
We talked about this last time, there is 4 diagrams that need to be done the sequence (which Anish is doing) and then 3 uml diagrams, I would just comment here to say what one you are going to do.

**Comment by CaitlinBerger** [comment]
I can do the class diagram for the intended class structure
